import {
  LucideArrowLeft,
  LucideArrowRight,
  LucideBaby,
  LucideBadgeCheck,
  LucideBookMarked,
  LucideBookOpen,
  LucideBookOpenCheck,
  LucideCalculator,
  LucideChartPie,
  LucideCheck,
  LucideChevronDown,
  LucideChevronLeft,
  LucideChevronRight,
  LucideCircleAlert,
  LucideCircleCheck,
  LucideCirclePlay,
  LucideClipboardCheck,
  LucideClipboardList,
  LucideClock,
  LucideDownload,
  LucideExternalLink,
  LucideFileCheck,
  LucideFileSearch,
  LucideFileSpreadsheet,
  LucideFileText,
  LucideGitBranch,
  LucideGlobe,
  LucideGraduationCap,
  LucideHeart,
  LucideInfo,
  LucideLanguages,
  LucideLibrary,
  LucideLightbulb,
  LucideListFilter,
  LucideLockKeyhole,
  LucideMail,
  LucideMenu,
  LucideMessageCircleQuestionMark,
  LucideMinus,
  LucideNetwork,
  LucidePercent,
  LucidePersonStanding,
  LucidePlus,
  LucidePrinter,
  LucideQuote,
  LucideRefreshCw,
  LucideScale,
  LucideShare2,
  LucideShield,
  LucideShieldCheck,
  LucideStar,
  LucideTag,
  LucideTriangleAlert,
  LucideUser,
  LucideUserCheck,
  LucideUserRound,
  LucideUserRoundX,
  LucideUserX,
  LucideUsers,
  LucideUsersRound,
  LucideWalletCards,
  LucideX,
} from '@lucide/angular';

/**
 * Every icon used by Mirath Guide, registered once so templates can
 * reference icons by name (see AppIconComponent) instead of importing a
 * Lucide component into every host component individually.
 */
export const APP_ICONS = {
  ArrowLeft: LucideArrowLeft,
  ArrowRight: LucideArrowRight,
  Baby: LucideBaby,
  BadgeCheck: LucideBadgeCheck,
  BookMarked: LucideBookMarked,
  BookOpen: LucideBookOpen,
  BookOpenCheck: LucideBookOpenCheck,
  Calculator: LucideCalculator,
  ChartPie: LucideChartPie,
  Check: LucideCheck,
  ChevronDown: LucideChevronDown,
  ChevronLeft: LucideChevronLeft,
  ChevronRight: LucideChevronRight,
  CircleAlert: LucideCircleAlert,
  CircleCheck: LucideCircleCheck,
  CirclePlay: LucideCirclePlay,
  ClipboardCheck: LucideClipboardCheck,
  ClipboardList: LucideClipboardList,
  Clock: LucideClock,
  Download: LucideDownload,
  ExternalLink: LucideExternalLink,
  FileCheck: LucideFileCheck,
  FileSearch: LucideFileSearch,
  FileSpreadsheet: LucideFileSpreadsheet,
  FileText: LucideFileText,
  GitBranch: LucideGitBranch,
  Globe: LucideGlobe,
  GraduationCap: LucideGraduationCap,
  Heart: LucideHeart,
  Info: LucideInfo,
  Languages: LucideLanguages,
  Library: LucideLibrary,
  Lightbulb: LucideLightbulb,
  ListFilter: LucideListFilter,
  LockKeyhole: LucideLockKeyhole,
  Mail: LucideMail,
  Menu: LucideMenu,
  MessageCircleQuestionMark: LucideMessageCircleQuestionMark,
  Minus: LucideMinus,
  Network: LucideNetwork,
  Percent: LucidePercent,
  PersonStanding: LucidePersonStanding,
  Plus: LucidePlus,
  Printer: LucidePrinter,
  Quote: LucideQuote,
  RefreshCw: LucideRefreshCw,
  Scale: LucideScale,
  Share2: LucideShare2,
  Shield: LucideShield,
  ShieldCheck: LucideShieldCheck,
  Star: LucideStar,
  Tag: LucideTag,
  TriangleAlert: LucideTriangleAlert,
  User: LucideUser,
  UserCheck: LucideUserCheck,
  UserRound: LucideUserRound,
  UserRoundX: LucideUserRoundX,
  UserX: LucideUserX,
  Users: LucideUsers,
  UsersRound: LucideUsersRound,
  WalletCards: LucideWalletCards,
  X: LucideX,
} as const;

export type AppIconName = keyof typeof APP_ICONS;
