import { ApprovedCaseFixture } from '../models/approved-case-fixture.model';

/**
 * Spec section 13B.7 - normative expected values. These fixtures are
 * reference-implementation verified and cross-checked against classical
 * worked examples, but are NOT yet scholar-approved (see verificationStatus).
 */
export const GOLDEN_FIXTURES: ApprovedCaseFixture[] = [
  {
    id: 'GF-01',
    description: 'Wife, 2 sons, 1 daughter, father, mother',
    answers: {
      deceasedGender: 'male',
      wivesCount: 1,
      hasDescendants: true,
      sonsCount: 2,
      daughtersCount: 1,
      fatherAlive: true,
      motherAlive: true,
    },
    expectedFinalShares: [
      { relationship: 'wife', numerator: 1, denominator: 8 },
      { relationship: 'mother', numerator: 1, denominator: 6 },
      { relationship: 'father', numerator: 1, denominator: 6 },
      { relationship: 'son', numerator: 13, denominator: 30 },
      { relationship: 'daughter', numerator: 13, denominator: 120 },
    ],
    expectedBlockedHeirs: [],
    verificationStatus: 'reference-implementation verified, scholarly review pending',
  },
  {
    id: 'GF-02',
    description: 'Minbariyya (Awl to 27): wife, 2 daughters, father, mother',
    answers: {
      deceasedGender: 'male',
      wivesCount: 1,
      hasDescendants: true,
      sonsCount: 0,
      daughtersCount: 2,
      fatherAlive: true,
      motherAlive: true,
    },
    expectedFinalShares: [
      { relationship: 'wife', numerator: 1, denominator: 9 },
      { relationship: 'daughter', numerator: 16, denominator: 27 },
      { relationship: 'mother', numerator: 4, denominator: 27 },
      { relationship: 'father', numerator: 4, denominator: 27 },
    ],
    expectedBlockedHeirs: [],
    expectedAdjustment: 'awl',
    verificationStatus: 'reference-implementation verified, scholarly review pending',
  },
  {
    id: 'GF-03',
    description: 'Umariyyatayn A: wife, father, mother',
    answers: { deceasedGender: 'male', wivesCount: 1, hasDescendants: false, fatherAlive: true, motherAlive: true },
    expectedFinalShares: [
      { relationship: 'wife', numerator: 1, denominator: 4 },
      { relationship: 'mother', numerator: 1, denominator: 4 },
      { relationship: 'father', numerator: 1, denominator: 2 },
    ],
    expectedBlockedHeirs: [],
    expectedAdjustment: 'umariyyatayn',
    verificationStatus: 'reference-implementation verified, scholarly review pending',
  },
  {
    id: 'GF-04',
    description: 'Umariyyatayn B: husband, father, mother',
    answers: { deceasedGender: 'female', husbandAlive: true, hasDescendants: false, fatherAlive: true, motherAlive: true },
    expectedFinalShares: [
      { relationship: 'husband', numerator: 1, denominator: 2 },
      { relationship: 'mother', numerator: 1, denominator: 6 },
      { relationship: 'father', numerator: 1, denominator: 3 },
    ],
    expectedBlockedHeirs: [],
    expectedAdjustment: 'umariyyatayn',
    verificationStatus: 'reference-implementation verified, scholarly review pending',
  },
  {
    id: 'GF-05',
    description: 'Umariyyatayn with ONE blocked sibling: wife, father, mother, 1 full brother',
    answers: {
      deceasedGender: 'male',
      wivesCount: 1,
      hasDescendants: false,
      fatherAlive: true,
      motherAlive: true,
      fullBrothersCount: 1,
    },
    expectedFinalShares: [
      { relationship: 'wife', numerator: 1, denominator: 4 },
      { relationship: 'mother', numerator: 1, denominator: 4 },
      { relationship: 'father', numerator: 1, denominator: 2 },
    ],
    expectedBlockedHeirs: [{ relationship: 'fullBrother' }],
    expectedAdjustment: 'umariyyatayn',
    verificationStatus: 'reference-implementation verified, scholarly review pending',
  },
  {
    id: 'GF-06',
    description: 'Mother reduced by two BLOCKED brothers: father, mother, 2 full brothers',
    answers: {
      deceasedGender: 'male',
      hasDescendants: false,
      fatherAlive: true,
      motherAlive: true,
      fullBrothersCount: 2,
    },
    expectedFinalShares: [
      { relationship: 'mother', numerator: 1, denominator: 6 },
      { relationship: 'father', numerator: 5, denominator: 6 },
    ],
    expectedBlockedHeirs: [{ relationship: 'fullBrother' }],
    verificationStatus: 'reference-implementation verified, scholarly review pending',
  },
  {
    id: 'GF-07',
    description: 'Awl to 8: husband, mother, 2 full sisters',
    answers: {
      deceasedGender: 'female',
      husbandAlive: true,
      hasDescendants: false,
      fatherAlive: false,
      paternalGrandfatherAlive: false,
      motherAlive: true,
      fullSistersCount: 2,
    },
    expectedFinalShares: [
      { relationship: 'husband', numerator: 3, denominator: 8 },
      { relationship: 'mother', numerator: 1, denominator: 8 },
      { relationship: 'fullSister', numerator: 1, denominator: 2 },
    ],
    expectedBlockedHeirs: [],
    expectedAdjustment: 'awl',
    verificationStatus: 'reference-implementation verified, scholarly review pending',
  },
  {
    id: 'GF-08',
    description: 'Awl to 7: husband, 2 full sisters',
    answers: {
      deceasedGender: 'female',
      husbandAlive: true,
      hasDescendants: false,
      fatherAlive: false,
      paternalGrandfatherAlive: false,
      motherAlive: false,
      fullSistersCount: 2,
    },
    expectedFinalShares: [
      { relationship: 'husband', numerator: 3, denominator: 7 },
      { relationship: 'fullSister', numerator: 4, denominator: 7 },
    ],
    expectedBlockedHeirs: [],
    expectedAdjustment: 'awl',
    verificationStatus: 'reference-implementation verified, scholarly review pending',
  },
  {
    id: 'GF-09',
    description: 'Radd never increases spouse: wife, 1 daughter',
    answers: { deceasedGender: 'male', wivesCount: 1, hasDescendants: true, sonsCount: 0, daughtersCount: 1 },
    expectedFinalShares: [
      { relationship: 'wife', numerator: 1, denominator: 8 },
      { relationship: 'daughter', numerator: 7, denominator: 8 },
    ],
    expectedBlockedHeirs: [],
    expectedAdjustment: 'radd',
    verificationStatus: 'reference-implementation verified, scholarly review pending',
  },
  {
    id: 'GF-10',
    description: 'Radd among blood heirs: mother, 1 daughter',
    answers: { deceasedGender: 'male', hasDescendants: true, sonsCount: 0, daughtersCount: 1, motherAlive: true },
    expectedFinalShares: [
      { relationship: 'mother', numerator: 1, denominator: 4 },
      { relationship: 'daughter', numerator: 3, denominator: 4 },
    ],
    expectedBlockedHeirs: [],
    expectedAdjustment: 'radd',
    verificationStatus: 'reference-implementation verified, scholarly review pending',
  },
  {
    id: 'GF-11',
    description: "Son's daughter completes 2/3: 1 daughter, 1 son's daughter, 1 full uncle",
    answers: {
      deceasedGender: 'male',
      hasDescendants: true,
      sonsCount: 0,
      daughtersCount: 1,
      paternalGrandsonsCount: 0,
      paternalGranddaughtersCount: 1,
      fatherAlive: false,
      paternalGrandfatherAlive: false,
      motherAlive: false,
      fullUnclesCount: 1,
    },
    expectedFinalShares: [
      { relationship: 'daughter', numerator: 1, denominator: 2 },
      { relationship: 'sonsDaughter', numerator: 1, denominator: 6 },
      { relationship: 'fullUncle', numerator: 1, denominator: 3 },
    ],
    expectedBlockedHeirs: [],
    verificationStatus: 'reference-implementation verified, scholarly review pending',
  },
  {
    id: 'GF-12',
    description: "Sister as asabah ma'a al-ghayr blocks half-brother: 1 daughter, 1 full sister, 1 paternal half-brother",
    answers: {
      deceasedGender: 'male',
      hasDescendants: true,
      sonsCount: 0,
      daughtersCount: 1,
      fatherAlive: false,
      paternalGrandfatherAlive: false,
      motherAlive: false,
      fullSistersCount: 1,
      paternalHalfBrothersCount: 1,
    },
    expectedFinalShares: [
      { relationship: 'daughter', numerator: 1, denominator: 2 },
      { relationship: 'fullSister', numerator: 1, denominator: 2 },
    ],
    expectedBlockedHeirs: [{ relationship: 'paternalHalfBrother' }],
    verificationStatus: 'reference-implementation verified, scholarly review pending',
  },
  {
    id: 'GF-13',
    description: 'Full sister alone does NOT block half-brother: 1 full sister, 1 paternal half-brother',
    answers: {
      deceasedGender: 'male',
      hasDescendants: false,
      fatherAlive: false,
      paternalGrandfatherAlive: false,
      motherAlive: false,
      fullSistersCount: 1,
      paternalHalfBrothersCount: 1,
    },
    expectedFinalShares: [
      { relationship: 'fullSister', numerator: 1, denominator: 2 },
      { relationship: 'paternalHalfBrother', numerator: 1, denominator: 2 },
    ],
    expectedBlockedHeirs: [],
    verificationStatus: 'reference-implementation verified, scholarly review pending',
  },
  {
    id: 'GF-14',
    description: 'Kalalah: husband, 1 maternal sibling, 1 full brother',
    answers: {
      deceasedGender: 'female',
      husbandAlive: true,
      hasDescendants: false,
      fatherAlive: false,
      paternalGrandfatherAlive: false,
      motherAlive: false,
      maternalSiblingsCount: 1,
      fullBrothersCount: 1,
    },
    expectedFinalShares: [
      { relationship: 'husband', numerator: 1, denominator: 2 },
      { relationship: 'maternalSibling', numerator: 1, denominator: 6 },
      { relationship: 'fullBrother', numerator: 1, denominator: 3 },
    ],
    expectedBlockedHeirs: [],
    verificationStatus: 'reference-implementation verified, scholarly review pending',
  },
  {
    id: 'GF-15',
    description: 'Mushtaraka, Hanafi: husband, mother, 2 maternal siblings, 1 full brother',
    answers: {
      deceasedGender: 'female',
      husbandAlive: true,
      hasDescendants: false,
      fatherAlive: false,
      paternalGrandfatherAlive: false,
      motherAlive: true,
      maternalSiblingsCount: 2,
      fullBrothersCount: 1,
    },
    expectedFinalShares: [
      { relationship: 'husband', numerator: 1, denominator: 2 },
      { relationship: 'mother', numerator: 1, denominator: 6 },
      { relationship: 'maternalSibling', numerator: 1, denominator: 3 },
    ],
    expectedBlockedHeirs: [{ relationship: 'fullBrother' }],
    verificationStatus: 'reference-implementation verified, scholarly review pending',
  },
  {
    id: 'GF-16',
    description: 'Grandfather blocks siblings, Hanafi: paternal grandfather, 2 full brothers',
    answers: {
      deceasedGender: 'male',
      hasDescendants: false,
      fatherAlive: false,
      paternalGrandfatherAlive: true,
      motherAlive: false,
      fullBrothersCount: 2,
    },
    expectedFinalShares: [{ relationship: 'paternalGrandfather', numerator: 1, denominator: 1 }],
    expectedBlockedHeirs: [{ relationship: 'fullBrother' }],
    verificationStatus: 'reference-implementation verified, scholarly review pending',
  },
  {
    id: 'GF-17',
    description: 'Full nephew blocks half nephew: wife, 1 full nephew, 3 half nephews',
    answers: {
      deceasedGender: 'male',
      wivesCount: 1,
      hasDescendants: false,
      fatherAlive: false,
      paternalGrandfatherAlive: false,
      motherAlive: false,
      fullNephewsCount: 1,
      halfNephewsCount: 3,
    },
    expectedFinalShares: [
      { relationship: 'wife', numerator: 1, denominator: 4 },
      { relationship: 'fullNephew', numerator: 3, denominator: 4 },
    ],
    expectedBlockedHeirs: [{ relationship: 'halfNephew' }],
    verificationStatus: 'reference-implementation verified, scholarly review pending',
  },
  {
    id: 'GF-18',
    description: 'Half nephew inherits: 1 daughter, 1 half nephew',
    answers: {
      deceasedGender: 'male',
      hasDescendants: true,
      sonsCount: 0,
      daughtersCount: 1,
      fatherAlive: false,
      paternalGrandfatherAlive: false,
      motherAlive: false,
      halfNephewsCount: 1,
    },
    expectedFinalShares: [
      { relationship: 'daughter', numerator: 1, denominator: 2 },
      { relationship: 'halfNephew', numerator: 1, denominator: 2 },
    ],
    expectedBlockedHeirs: [],
    verificationStatus: 'reference-implementation verified, scholarly review pending',
  },
  {
    id: 'GF-19',
    description: 'Full uncle blocks half uncle: wife, 1 full uncle, 2 half uncles',
    answers: {
      deceasedGender: 'male',
      wivesCount: 1,
      hasDescendants: false,
      fatherAlive: false,
      paternalGrandfatherAlive: false,
      motherAlive: false,
      fullUnclesCount: 1,
      halfUnclesCount: 2,
    },
    expectedFinalShares: [
      { relationship: 'wife', numerator: 1, denominator: 4 },
      { relationship: 'fullUncle', numerator: 3, denominator: 4 },
    ],
    expectedBlockedHeirs: [{ relationship: 'halfUncle' }],
    verificationStatus: 'reference-implementation verified, scholarly review pending',
  },
  {
    id: 'GF-20',
    description: 'Spouse only: husband, no other relatives',
    answers: { deceasedGender: 'female', husbandAlive: true, hasDescendants: false },
    expectedFinalShares: [{ relationship: 'husband', numerator: 1, denominator: 2 }],
    expectedBlockedHeirs: [],
    verificationStatus: 'reference-implementation verified, scholarly review pending',
  },
];
